### ISSUE TITLE
cpp/uninitialized-local: False positive

### ISSUE THREAD

**Issue by chrfranke** [github/codeql#12488] opened 2023-03-10 18:27 UTC
**Description of the false positive**

Control flow of uninitialized variable does not reach first usage of variable due to early return (possibly related/duplicate: #12487). The second `if` is only reached if the condition of the first `if`is false. This implies that the last part of the `&& ... &&` expression which sets `pid` is executed.

```cpp
  pid_t pid;
  // ...
  if (!(// Create stdout and status pipe ...
        !pipe(pd) && !pipe(sd) &&
        // ... connect stdout pipe to FILE ...
        !!(fp = fdopen(pd[0], "r")) &&
        // ... and then fork()
        (pid = fork()) != (pid_t)-1)  ) {
    // ...
    return (FILE *)0;
  }

  if (!pid) { // Child
```

**Code samples or links to source code**

https://github.com/smartmontools/smartmontools/blob/ace484f1ffb626bae21bb182df8b1b86cd1f2b4e/smartmontools/popen_as_ugid.cpp#L45-L67

**URL to the alert on GitHub code scanning (optional)**

https://github.com/smartmontools/smartmontools/security/code-scanning/77

**Comment by ryao** [comment] 2023-03-12 00:11
This might be related to or a duplicate of #11240.

**Closed** 2023-03-13 14:30 UTC
Labels: false-positive
