### ISSUE TITLE
LGTM.com - false positive - Wrong type of arguments to formatting function

### ISSUE THREAD

**Issue by CrendKing** [github/codeql#4505] opened 2020-10-19 06:16 UTC
**Description of the false positive**

In C++ code, I have a log function that has the same signature as printf. When called with
```
Log("Test: %2i", test_int);
```
I get error saying
```
This argument should be of type 'int' but is of type 'error' 
```
Coincidentally, every one of them directly (using `operator*()`) or indirectly (define an `int` with the optional value and print it) involves `std::optional<int>`.

**URL to the alert on the project page on LGTM.com**

[My project](https://github.com/CrendKing/avisynth_filter/) is not on LGTM.

**Comment by CrendKing** [comment] 2020-10-19 08:52
FYI, the source file lines of this report:

https://github.com/CrendKing/avisynth_filter/blob/master/avisynth_filter/src/filter.cpp#L130
https://github.com/CrendKing/avisynth_filter/blob/master/avisynth_filter/src/filter.cpp#L140
https://github.com/CrendKing/avisynth_filter/blob/master/avisynth_filter/src/filter.cpp#L163
https://github.com/CrendKing/avisynth_filter/blob/master/avisynth_filter/src/filter.cpp#L193
https://github.com/CrendKing/avisynth_filter/blob/master/avisynth_filter/src/filter.cpp#L250
https://github.com/CrendKing/avisynth_filter/blob/master/avisynth_filter/src/filter.cpp#L258
https://github.com/CrendKing/avisynth_filter/blob/master/avisynth_filter/src/filter.cpp#L261
https://github.com/CrendKing/avisynth_filter/blob/master/avisynth_filter/src/filter.cpp#L469

**Comment by geoffw0** [comment] 2020-10-20 11:55
Hi, it _looks_ like the extractor may be failing to understand something near the uses of `std::optional` - but it's difficult to be sure without access to the snapshot (e.g. on LGTM).  I looked at some other snapshots and had a go at reproducing this locally, but I didn't encounter the problem.

A starting point to debugging it might be to run the `cpp/non-portable-printf` query on your project, but modified to output `concat(actual.getAQlClass(), ", ")` alongside each result so that we can see whether an `ErroneousType` or something else is producting the text `"error"` (`getAQlClass()` is a debugging tool that outputs the leaf QL classes associated with something).

**Comment by CrendKing** [comment] 2020-10-21 03:30
Thanks. I'm not sure how to make my project run in LGTM, as its autobuild script does not work because my project requires Visual Studio and MSBuild.

I downloaded CodeQL and ran the query locally, and I can reproduce the same message. Then I added the string you mentioned (I believe the file I needed to change is `WrongTypeFormatArguments.ql`, not `NonPortablePrintf.ql`). And yes, the "error" is produced by `ErroneousType`.

Is there anything else I can help? Same as you, I tried to make a minimum product to reproduce the issue but failed. So I wonder if you have a Windows machine and Visual Studio 2019 installed? If so, I can tell you how to create the DB from my project, or you can download the DB I created: https://mega.nz/file/ApIixL4J#to02CmGfULNcftQ3F0TTFQOEfVzu6uW9FDf-rx-q0_U

**Comment by geoffw0** [comment] 2020-10-21 14:13
Hi,

Thank you for the snapshot.  It looks like during the build there were compile errors, specifically:
```
namespace 'std' has no member 'optional'
namespace 'std' has no member 'nullopt'
namespace 'std' has no member 'gcd'
```
I believe the `ErroneousType`s originate from these errors.  I know that both are from C++17 so there may be an issue related to that.

I've created https://github.com/github/codeql/pull/4532 that makes the query a bit more robust against cases like these.  We're also discussing the underlying causes, but you should see the results disappear when you get that change.

**Comment by CrendKing** [comment] 2020-10-21 18:15
If it is related to C++ 17, why does a minimum code such as
```
#include <optional>

auto f() -> std::optional<int> {
	return std::nullopt;
}

auto main(int argc, char *argv[]) -> int {
	if (const std::optional<int> opt = f()) {
		printf("%2i", *opt);
	}
	return 0;
}
```
not able to trigger?

**Comment by geoffw0** [comment] 2020-10-22 14:33
> If it is related to C++ 17, why does a minimum code such as ... not able to trigger?

It looks to be a more complicated problem.  We're investigating.

https://github.com/github/codeql/pull/4532 has been merged, you should no longer see these 'error' results once that reaches you.

**Comment by geoffw0** [comment] 2020-10-22 15:03
> So I wonder if you have a Windows machine and Visual Studio 2019 installed? If so, I can tell you how to create the DB from my project, or you can download the DB I created: https://mega.nz/file/ApIixL4J#to02CmGfULNcftQ3F0TTFQOEfVzu6uW9FDf-rx-q0_U

At this point it would be useful if we could create the DB ourselves - please could I have these instructions?

**Comment by CrendKing** [comment] 2020-10-22 18:14
Of course.

1. Make sure you have a Windows machine with Visual Studio 2019 installed. I think ATL also needed.
2. Download the CodeQL bundle from https://github.com/github/codeql-action/releases. I tried https://github.com/github/codeql-cli-binaries/releases/tag/v2.3.1 first, thought it's the latest must be good. But when analyze it gave me error saying "The database may be too new for the QL libraries the query is using. Please upgrade". The bundle seems working properly.
3. Git clone https://github.com/CrendKing/avisynth_filter.git
4. Launch a command line with VS environment. For example, in PowerShell, do `Import-Module 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\Microsoft.VisualStudio.DevShell.dll'; Enter-VsDevShell cb212265`.
5. `codeql database init <database> --language=cpp --source-root=<avisynth_filter path>`
6. `codeql database trace-command <database> <avisynth_filter path>\build.bat x64`
7. `codeql database finalize <database>`

That should be it. Note that because the project depends on one external dependency statically, `build.bat` will check it out and build from source, so the database will also have data about it. To have a more cleaner version, run `build.bat x64` first. Then go delete the `x64` directory in `avisynth_filter` subdirectory. Then run step 5-7.

Let me know if anything goes wrong.

**Comment by jbj** [comment] 2020-11-09 10:55
@CrendKing Thank you for the build instructions (I hope the last three steps can be merged into one `codeql database create`). We'll use them to diagnose the underlying problem.

Can you confirm that the false positives disappear when using a version of github/codeql that includes https://github.com/github/codeql/pull/4532? Using the `main` branch should be good, and using the an updated submodule of https://github.com/github/vscode-codeql-starter should also be good (in case you set up that repo as part of your VSCode extension installation). If the problem isn't fixed, please reopen this issue.

**Closed by jbj** 2020-11-09 10:55 UTC
Labels: C++, false-positive

**Comment by CrendKing** [comment] 2020-11-09 16:04
The false positives went away.

**Comment by CrendKing** [comment] 2020-11-10 10:24
@jbj Actually I just ran the workflow once and all the errors are back. I don't know what `main` or the submodule you mentioned. I just use the GitHub action workflow. And I can't reopen this issue.
