### ISSUE TITLE
Problems with C/C++-Autobuild System

### ISSUE THREAD

**Issue by puya-pakshad** [github/codeql#12222] opened 2023-02-16 22:18 UTC
### Discussed in https://github.com/github/codeql/discussions/11735

<div type='discussions-op-text'>

<sup>Originally posted by **mutasDev** December 19, 2022</sup>
Hey Fellows,

I am trying to create a Codeql-DB for a set of C files all lying in one subdirectory. Each of the files is a single .c file without dependencies on each other.

Some weeks/months ago I was able to create a C-Database out of the files with invoking the CodeQL-cli without specifying a build command.

The command I use is : 

`codeql database create $dbname$ --language=cpp --source-root="$sourceroot$"`

When I try to create the database now, I stumble upon the following error, can anybody narrow the mistake down for me? 

```Running build command: [/opt/homebrew/Caskroom/codeql/2.11.2/codeql/cpp/tools/autobuild.sh]
[2022-12-19 10:19:20] [build-stderr] + TOOLS_DIR=/opt/homebrew/Caskroom/codeql/2.11.2/codeql/cpp/tools
[2022-12-19 10:19:20] [build-stderr] + /opt/homebrew/Caskroom/codeql/2.11.2/codeql/cpp/tools/detect_source_root
[2022-12-19 10:19:20] [build-stdout] detect_source_root: Build will be attempted from '.'
[2022-12-19 10:19:20] [build-stdout] even though no build system was found there.
[2022-12-19 10:19:20] [build-stderr] + '[' -L _lgtm_detected_source_root ']'
[2022-12-19 10:19:20] [build-stderr] ++ readlink _lgtm_detected_source_root
[2022-12-19 10:19:20] [build-stderr] + cd .
[2022-12-19 10:19:20] [build-stderr] + export CXXFLAGS=-fpermissive
[2022-12-19 10:19:20] [build-stderr] + CXXFLAGS=-fpermissive
[2022-12-19 10:19:20] [build-stderr] + configure_prefix_opt=
[2022-12-19 10:19:20] [build-stderr] + '[' -f configure.ac ']'
[2022-12-19 10:19:20] [build-stderr] + '[' -f configure.in ']'
[2022-12-19 10:19:20] [build-stderr] + '[' -f CMakeLists.txt ']'
[2022-12-19 10:19:20] [build-stderr] + '[' -f meson.build ']'
[2022-12-19 10:19:20] [build-stderr] + try_configure
[2022-12-19 10:19:20] [build-stderr] + build_dir=.
[2022-12-19 10:19:20] [build-stderr] + root_dir=.
[2022-12-19 10:19:20] [build-stderr] + grep -q 'AC_MSG_.* configure in a separate.* directory' configure.in configure.ac
[2022-12-19 10:19:20] [build-stderr] + for configure in configure configure.gnu
[2022-12-19 10:19:20] [build-stderr] + '[' -x configure ']'
[2022-12-19 10:19:20] [build-stderr] + for configure in configure configure.gnu
[2022-12-19 10:19:20] [build-stderr] + '[' -x configure.gnu ']'
[2022-12-19 10:19:20] [build-stderr] + rm -rf _lgtm_build_dir
[2022-12-19 10:19:20] [build-stderr] + for bootstrap in bootstrap.sh bootstrap autogen.sh
[2022-12-19 10:19:20] [build-stderr] + '[' -x bootstrap.sh ']'
[2022-12-19 10:19:20] [build-stderr] + '[' -f bootstrap.sh ']'
[2022-12-19 10:19:20] [build-stderr] + for bootstrap in bootstrap.sh bootstrap autogen.sh
[2022-12-19 10:19:20] [build-stderr] + '[' -x bootstrap ']'
[2022-12-19 10:19:20] [build-stderr] + '[' -f bootstrap ']'
[2022-12-19 10:19:20] [build-stderr] + for bootstrap in bootstrap.sh bootstrap autogen.sh
[2022-12-19 10:19:20] [build-stderr] + '[' -x autogen.sh ']'
[2022-12-19 10:19:20] [build-stderr] + '[' -f autogen.sh ']'
[2022-12-19 10:19:20] [build-stderr] + '[' -f wscript ']'
[2022-12-19 10:19:20] [build-stderr] + '[' -f Kbuild ']'
[2022-12-19 10:19:20] [build-stderr] + '[' -f configure.ac ']'
[2022-12-19 10:19:20] [build-stderr] + '[' -f configure.in ']'
[2022-12-19 10:19:20] [build-stderr] ++ echo './*.pro'
[2022-12-19 10:19:20] [build-stderr] + '[' './*.pro' '!=' './*.pro' ']'
[2022-12-19 10:19:20] [build-stderr] + exit 0
[2022-12-19 10:19:20] [build-stderr] + export VERBOSE=1
[2022-12-19 10:19:20] [build-stderr] + VERBOSE=1
[2022-12-19 10:19:20] [build-stderr] + '[' -L _lgtm_detected_source_root ']'
[2022-12-19 10:19:20] [build-stderr] ++ readlink _lgtm_detected_source_root
[2022-12-19 10:19:21] [build-stderr] + cd .
[2022-12-19 10:19:21] [build-stderr] + '[' -d _lgtm_build_dir ']'
[2022-12-19 10:19:21] [build-stderr] + '[' -f SConstruct ']'
[2022-12-19 10:19:21] [build-stderr] + '[' -f wscript ']'
[2022-12-19 10:19:21] [build-stderr] + '[' -f Makefile ']'
[2022-12-19 10:19:21] [build-stderr] + '[' -f makefile ']'
[2022-12-19 10:19:21] [build-stderr] + '[' -f GNUmakefile ']'
[2022-12-19 10:19:21] [build-stderr] + '[' -f build.ninja ']'
[2022-12-19 10:19:21] [build-stderr] + '[' -d ../_lgtm_build_dir ']'
[2022-12-19 10:19:21] [build-stdout] Semmle autobuild: no supported build system detected.
[2022-12-19 10:19:21] [build-stderr] + for f in build build.sh
[2022-12-19 10:19:21] [build-stderr] + '[' -x build ']'
[2022-12-19 10:19:21] [build-stderr] + for f in build build.sh
[2022-12-19 10:19:21] [build-stderr] + '[' -x build.sh ']'
[2022-12-19 10:19:21] [build-stderr] + '[' -f setup.py ']'
[2022-12-19 10:19:21] [build-stderr] + echo 'Semmle autobuild: no supported build system detected.'
[2022-12-19 10:19:21] [build-stderr] + exit 1
[2022-12-19 10:19:21] [ERROR] Spawned process exited abnormally (code 1; tried to run: [/opt/homebrew/Caskroom/codeql/2.11.2/codeql/tools/osx64/preload_tracer, /opt/homebrew/Caskroom/codeql/2.11.2/codeql/cpp/tools/autobuild.sh])
A fatal error occurred: Exit status 1 from command: [/opt/homebrew/Caskroom/codeql/2.11.2/codeql/cpp/tools/autobuild.sh] 

```

</div>

**Comment by alexet** [comment] 2023-02-17 12:15
What build system are you using, we support `cmake`, `qmake`, `kconfig`, `scons`, `waf` `make`, `ninja`, and scrips called `build.sh`/`build`.

**Comment by jketema** [comment] 2023-02-18 19:34
Closing this as a copy & paste duplicate of https://github.com/github/codeql/discussions/11735

**Closed by jketema** 2023-02-18 19:34 UTC
