### ISSUE TITLE
cpp/uninitialized-local: False positive

### ISSUE THREAD

**Issue by chrfranke** [github/codeql#12487] opened 2023-03-10 18:16 UTC
**Description of the false positive**

Control flow of uninitialized variable does not reach first usage of variable due to early return (possibly related/duplicate: https://github.com/github/codeql/issues/12488). If `version` is not initialized, `n1 < 0` is always true and functions returns early before first usage of `version`

```cpp
  int n1 = -1;
  // ... (may set n1 > 0) ...
  uint8_t version;
  if (!strcmp(prefix, "jmb39x"))
    version = 0;
  else if (!strcmp(prefix, "jmb39x-q"))
    version = 1;
  else if (!strcmp(prefix, "jms56x"))
    version = 2;
  else
    n1 = -1;
  if (n1 < 0) {
    set_err(EINVAL, "Unknown JMicron type '%s'", type);
    return 0;
  }
  // ...
  ata_device * jmbdev = new jmb39x::jmb39x_device(..., version, ...);
```

**Code samples or links to source code**

https://github.com/smartmontools/smartmontools/blob/ace484f1ffb626bae21bb182df8b1b86cd1f2b4e/smartmontools/dev_jmb39x_raid.cpp#L700-L737

**URL to the alert on GitHub code scanning (optional)**

https://github.com/smartmontools/smartmontools/security/code-scanning/76

**Comment by ryao** [comment] 2023-03-12 00:11
This might be related to or a duplicate of #11240.

**Comment by smowton** [comment] 2023-03-13 14:29
Agree with @ryao -- see @MathiasVP's commentary at https://github.com/github/codeql/issues/11240

**Closed** 2023-03-13 14:30 UTC
Labels: false-positive
