### ISSUE TITLE
C#: Support for C# 9

### ISSUE THREAD

**Issue by muiriswoulfe** [github/codeql#5096] opened 2021-02-04 17:12 UTC
**Description of the issue**

CodeQL doesn't support [C# 9](https://docs.microsoft.com/dotnet/csharp/whats-new/csharp-9) -- the latest version. When new C# 9-only features are used, a "compilation error" message is reported with a message akin to the following:

```
Error CS8652 The feature 'not pattern' is currently in Preview and unsupported. To use Preview features, use the 'preview' language version.
```

You can see these issues repro for my repo at <https://github.com/muiriswoulfe/NuGet-Transitive-Dependency-Finder>.

I'm also seeing issues around having [`<Nullable>enable</Nullable>`](https://docs.microsoft.com/dotnet/csharp/language-reference/builtin-types/nullable-reference-types) set for my project, but I feel that one fix might resolve both issues.

I believe/hope that this issue can just be resolved by updating the version of the Roslyn library used by CodeQL. There may be some work required for some rules, but hopefully a simple library update can address the vast majority of issues.

**Comment by hvitved** [comment] 2021-02-05 07:32
Hi Muiris

Thank you for reporting this. We are actively working on supporting C# 9 at the moment, for example extraction of `not` patterns got merged [3 weeks ago](https://github.com/github/codeql/pull/4656). However, we already upgraded to the latest version of Roslyn [back in November](https://github.com/github/codeql/pull/4666), so I am surprised that you get the error above.

Could you elaborate on how to reproduce the error?

Thanks

Tom

**Comment by muiriswoulfe** [comment] 2021-02-05 20:34
Thanks for getting back to me @hvitved. That's strange -- the "old C# version" errors first appeared in a branch I created some time ago, probably prior to the November change. I ignored the errors at the time, but then after merging the branch with main, the GitHub project started reporting the issues in the main branch.

Perhaps GitHub just retained the issues from the old branch. I would have expected the issues to have been detected during the main build before marking them as active for the main branch, but perhaps it works differently than that. I've now deleted all of these issues and they hopefully won't reappear.

**Comment by hvitved** [comment] 2021-02-08 08:17
I'm still curious where you saw the errors; were they in the Actions build logs when running CodeQL scanning? If so, they are not logged by CodeQL, but rather the build itself. And if this was prior to the [release of .NET 5 on November 10th](https://github.com/dotnet/core/blob/master/release-notes/5.0/5.0.0/5.0.0.md), then I guess the problem was that .NET 5 was not installed in the image used by Actions.

**Comment by muiriswoulfe** [comment] 2021-02-08 19:02
Unfortunately, I can't find them anymore, but I'm pretty sure they were logged by CodeQL. I had explicitly set up the pipeline to use .NET 5 at the time I was using these (which was subsequent to the official release) so there should have been no problem with the Actions build.

The good news though is that the issue really seems to have gone away now. I pushed a new commit to main and the issues did not recur, so I believe we can close this issue.

**Closed** 2021-02-08 19:49 UTC
Labels: C#, question
