### ISSUE TITLE
Report says the pipeline failed but the logs say everything passed

### ISSUE THREAD

**Issue by davfsa** [github/codeql#3787] opened 2020-06-24 18:16 UTC
**Description of the issue**
Our pipelines have started failing because LGTM says that the pipelines have failed in the report, but looking at the logs everything is fine.

[Report](https://lgtm.com/projects/gl/nekokatt/hikari/rev/pr-4de2cb60792a8e0f8991de65fef5c175eb896d59)
[Logs](https://lgtm.com/projects/gl/nekokatt/hikari/logs/rev/pr-4de2cb60792a8e0f8991de65fef5c175eb896d59/lang:python/stage:Preparing%20merge%20commit_3369b26927d47bad77b9af4c2744acc0b0aed1e9)
[Repository](https://gitlab.com/nekokatt/hikari)

**Comment by chrisgavin** [comment] 2020-06-24 19:37
Hi. Thank you for reporting this issue. It was caused by an error while comparing the results of the build for your default branch against the build for the pull request.

We have now resolved this error and rerun the analysis on your pull request. We are also currently restarting analyses on other affected pull requests so any other pull requests you may have with a similar issue should be fixed shortly.

Sorry for any inconvenience this has caused.

**Closed** 2020-06-24 19:39 UTC
Labels: question

**Comment by davfsa** [comment] 2020-06-24 19:59
Thx a lot :+1:
