### ISSUE TITLE
Merge conflicts on LGTM when merge conflicts don't exist in-code

### ISSUE THREAD

**Issue by ghost** [github/codeql#2477] opened 2019-12-01 11:43 UTC
For some reason, branches are being merged on LGTM rather than just reset to the state of the repository that is triggering the webhooks to perform the LGTM job.

This leads to merge conflicts apparently occuring when my code base does not actually have merge conflicts.

Log: https://lgtm.com/projects/gl/nekokatt/hikari/logs/rev/pr-2ebdfe1e8aaed489001e3b9e8a2c8c6827cc7f7d/lang:javascript/stage:Preparing%20merge%20commit_c3e1e0455e1cf44e57eab56b4843abf3247b939e

Failing job on GitLab CI: https://gitlab.com/nekokatt/hikari/pipelines/99760661

![image](https://user-images.githubusercontent.com/52883826/69913442-ce934d80-142f-11ea-99d7-34f92dcaeaba.png)

**Comment by rneatherway** [comment] 2019-12-05 14:30
Hi @nekokatt,

> For some reason, branches are being merged on LGTM rather than just reset to the state of the repository that is triggering the webhooks to perform the LGTM job.

Yes, this is a deliberate decision so that you are seeing the results of the analysis of what the state of the repository will be _if_ the PR is merged.

I've taken a look at the log that you linked, and at the end we see that

> [2019-12-01 11:37:23] [ERROR] Spawned process exited abnormally (code 1; tried to run: [git, merge, --no-ff, c3e1e0455e1cf44e57eab56b4843abf3247b939e, -m, lgtm: Merge of c3e1e0455e1cf44e57eab56b4843abf3247b939e into 203b6baf2f372a8947b38f873dc059c7695ec327])

So at the time this analysis was run, the HEAD of `master` was `203b6baf2f372a8947b38f873dc059c7695ec327`, and the head of the PR branch was `c3e1e0455e1cf44e57eab56b4843abf3247b939e`. I've checked locally and these did indeed show merge conflicts, so I believe that LGTM is behaving as intended.

I think that you resolved this when [merging in from staging](https://gitlab.com/nekokatt/hikari/compare/c3e1e0455e1cf44e57eab56b4843abf3247b939e...203b6baf2f372a8947b38f873dc059c7695ec327).

**Closed** 2022-02-16 14:17 UTC
Labels: question
