### ISSUE TITLE
LGTM.com - false positive

### ISSUE THREAD

**Issue by robinwatts** [github/codeql#3597] opened 2020-06-01 11:45 UTC
C string within a python file is being reported as a python 3 syntax error. The file runs just fine under python 3.

https://lgtm.com/projects/g/ArtifexSoftware/mupdf/snapshot/d6ae62355c2fd0d2c008f0a189f24720d7185916/files/scripts/mupdfwrap.py?sort=name&dir=ASC&mode=heatmap#x11c684df9e2552ed:1

**Comment by tausbn** [comment] 2020-06-01 12:33
This is a duplicate of #3588. The underlying issue has been fixed, and the fix should go live in a week or so.

**Closed by tausbn** 2020-06-01 12:33 UTC
Labels: Python, false-positive
