### ISSUE TITLE
False positive - Python: "Statement has no effect" for typing.overload function body

### ISSUE THREAD

**Issue by mauvilsa** [github/codeql#11629] opened 2022-12-08 20:06 UTC
**Description of the false positive**

In Python when adding type hints to the source code, it is possible to have multiple function definitions for different combinations of types, and the body of the function is ignored, so commonly set to `...`, see https://docs.python.org/3/library/typing.html#typing.overload. These overloaded function bodies are identified as "Statement has no effect". Indeed they are statements with no effect, however, this is how it is supposed to be done. Thus, I would say codeql should ignore these. Note that it is okay to have these overload defs in `*.py` files, not just in type stub files.

**Code samples or links to source code**

I reproduced this locally with codeql CLI, using a script with content (the python docs example linked above):

```python
from typing import overload, Tuple

@overload
def process(response: None) -> None:
    ...
@overload
def process(response: int) -> Tuple[int, str]:
    ...
@overload
def process(response: bytes) -> str:
    ...
def process(response):
    if isinstance(response, int):
        return response, str(response)
    elif isinstance(response, bytes):
        return response.decode()
    return None
```

Then I ran:

```shell
codeql database create --language=python python-database
codeql database analyze python-database \
  $HOME/.codeql/packages/codeql/python-queries/0.5.5/Statements/StatementNoEffect.ql \
  --format=sarif-latest \
  --output=python-results.sarif.txt
```

[python-results.sarif.txt](https://github.com/github/codeql/files/10189094/python-results.sarif.txt)

**URL to the alert on GitHub code scanning (optional)**

https://github.com/omni-us/jsonargparse/security/code-scanning/120

**Comment by intrigus-lgtm** [comment] 2022-12-08 21:42
I _think_ this is a duplicate of https://github.com/github/codeql/issues/11351

**Closed** 2022-12-08 21:51 UTC
Labels: false-positive
