### ISSUE TITLE
Java: Extractor does not properly report type conversion compilation errors for `codeql test run`

### ISSUE THREAD

**Issue by Marcono1234** [github/codeql#10118] opened 2022-08-19 16:50 UTC
Might be similar to #5476

**Version**
CodeQL CLI 2.10.3

**Description of the issue**
It appears the Java extractor executed as part of `codeql test run` does not properly detect compilation errors in the Java source code due to invalid type conversion.
Instead it logs the following and fails compilation:
```
[2022-08-19 18:42:57] [javac-extractor-7024] Writing trap file for: <any> -1.-1-0 null
[2022-08-19 18:42:57] [javac-extractor-7024] [WARN] Unknown location for <any>
[2022-08-19 18:42:57] [javac-extractor-7024] [ERROR] Exception compiling file Test.java
                                                     com.semmle.util.exception.ResourceError: Couldn't rename #redacted#.testproj\trap\java\classes\_any_.members.trap.gz.tmp to #redacted#.testproj\trap\java\classes\<any>.members.trap.gz
                                                     	at com.semmle.util.trap.TrapWriter.close(TrapWriter.java:506)
                                                     	at com.semmle.extractor.java.OdasaOutput$JavaTrapWriter.close(OdasaOutput.java:347)
                                                     	at com.semmle.extractor.java.OnDemandExtractor.extract(OnDemandExtractor.java:130)
                                                     	at com.semmle.extractor.java.CompilationUnitExtractor.process(CompilationUnitExtractor.java:81)
                                                     	at com.semmle.extractor.java.JavaExtractor.runExtractor(JavaExtractor.java:336)
                                                     	at com.semmle.extractor.java.JavaExtractor.main(JavaExtractor.java:486)
```
Note how this is not a proper `javac` compilation error, but instead the CodeQL Java extractor fails because it tries to create a file named `<any>.members.trap.gz` which is not a valid file name on Windows. (Have not tested how this behaves on Linux.)

**Reproduction steps**
Assumes you already have a project with the Java library present; you could for example use https://github.com/github/codeql and perform the following in the test directory of it.

1. Create a test directory with the following `Test.java` file:
    ```java
    class Test {
        // This should cause a compilation error
        Number o = "";
    }
    ```
    As indicated by the comments, the file causes compilation errors which can be seen when running `javac`.
2. Create a `Test.ql` file (content does not matter much), e.g.:
    ```ql
    import java

    from Element e
    where e.fromSource()
    select e
    ```
3. Execute the test, either by running `codeql test run` or by using the VSCode extension
    :x: Test execution fails with a `ResourceError` instead of properly reporting the compilation error

**Comment by smowton** [comment] 2022-08-19 18:21
Thanks for the report -- it looks to me as if there are two independent problems, one of inconsistently limiting the charset of trap filenames, seen in the `.tmp` filename but not the final one, and separately the hazards of trying to extract a database based on files that don't compile. That latter is a known issue in other contexts and I intend to look at it next week, so this may get fixed incidentally.

**Comment by 477447** [comment] 2022-08-21 19:59
BANK

**Comment by smowton** [comment] 2023-04-12 17:33
As of CodeQL 2.12.5 I can confirm this no longer attempts to write a file named `<any>.trap.gz`, which stemmed from inappropriately trying to extract erroneous types. More accurate stub types are now extracted instead, as described at https://github.com/github/codeql/issues/11264

In addition, an extraction error now occurs with the logs indicating the reason was `javac` correctly failing to compile a test `.java` file.

**Closed by smowton** 2023-04-12 17:33 UTC
Labels: question

**Comment by 477447** [comment] 2023-07-10 14:25
e
