### ISSUE TITLE
LGTM.com - false positive

### ISSUE THREAD

**Issue by d-frey** [github/codeql#3492] opened 2020-05-17 15:22 UTC
**Description of the false positive**

The warning is:

`Function match should return a value of type bool but does not return a value here`

The function itself is marked `[[noreturn]]`, as is the method we are calling (`raise`), hence the function is never expected to return a value at all, it will always return with an exception.

**URL to the alert on the project page on LGTM.com**

https://lgtm.com/projects/g/taocpp/PEGTL/snapshot/fb658947551178136cff7325b0683233d26bf28e/files/include/tao/pegtl/internal/raise.hpp?sort=name&dir=ASC&mode=heatmap#x4569b92e5b010027:1

**Comment by jbj** [comment] 2020-05-19 08:05
Thanks for the report. This looks like a duplicate of https://github.com/github/codeql/issues/3327, so I'll close it as such. @dbartol, can you post a progress update to https://github.com/github/codeql/issues/3327?

**Closed by jbj** 2020-05-19 08:05 UTC
Labels: C++, false-positive
