### ISSUE TITLE
Issues uploading Sarif file "Problems parsing JSON"

### ISSUE THREAD

**Issue by sla-1** [github/codeql#16706] opened 2024-06-07 17:32 UTC
This just started happening today around ~4am PST time before that codeql was uploading just fine. We were on codeql CLI version 2.17.0. We tried updating to the latest codeql version 2.17.4 and we're hitting the same error. 

```
10:26:02  + codeql github upload-results --ref=refs/pull/{PR}/head --sarif=/home/javascript-results.sarif
10:26:05  A fatal error occurred: Error uploading SARIF to 'https://api.github.com/repos/delphix/devops-gate/code-scanning/sarifs' from '/home/javascript-results.sarif'. REASON: HTTP/1.1 400 Bad Request:::{"message":"Problems parsing JSON","documentation_url":"https://docs.github.com/rest/code-scanning/code-scanning#upload-an-analysis-as-sarif-data"}
```

Thanks,
Steven

**Comment by sla-1** [comment] 2024-06-07 21:33
Looks like uploads started working again. Was someone fix on the api endpoint?

**Comment by gsolic** [comment] 2024-06-11 07:44
We also saw the same error response from the API on our builds, especially when you are using the CodeQL cli tool (`codeql github upload-results`) to upload the results. The workflow action `github/codeql-action/upload-sarif@v3` worked as expected without an uploading error. We also tried to upgrade CodeQL CLI from version `2.13.5` to `2.17.4` without any luck.

The problem seems to be fixed now and `codeql github upload-results` is working again.

**Comment by mbg** [comment] 2024-06-19 11:06
Hi @sla-1 and @gsolic 👋 

Thanks for reporting this and posting an update to say things are working again for you. Sorry nobody had replied to you here sooner. 

This seems to have been related to an issue caused by an internal software update that took place a little before you reported this, unrelated to CodeQL or the specific API endpoint. I can confirm that the issue has been fixed since and will close this issue now.

If you encounter any problems again with this, feel free to re-open this issue or open a new one.

**Closed by mbg** 2024-06-19 11:06 UTC
Labels: question
