### ISSUE TITLE
Minor doc issue in Python "Tutorials: Statements and Expressions"

### ISSUE THREAD

**Issue by lgolding** [github/codeql#3361] opened 2020-04-27 15:11 UTC
On https://help.semmle.com/QL/learn-ql/python/statements-expressions.html, in the section “Example: Finding comparisons to integer or string literals using ‘is’”, the Tip says:

… the expression `3 < x < 7` has two operators and two comparators. You use `cmp.getComparator(0)` to get the first comparator (in this example the `3`) and `cmp.getComparator(1)` to get the second comparator (in this example the `7`).

But `getComparator(0)` returns the `x`, not the `3`. To get the `3`, you call `getLeft()`.

**Comment by RasmusWL** [comment] 2020-04-29 16:02
Closing as this is a duplicate of #3360

**Closed by RasmusWL** 2020-04-29 16:02 UTC
Labels: Python, duplicate, question
