### ISSUE TITLE
Add me to the organisaton

### ISSUE THREAD

**Issue by vedantmgoyal2009** [github/codeql#6105] opened 2021-06-18 11:24 UTC
Hi there,
My GitHub Username -&nbsp;@vedantmgoyal2009
Please add me to the organisation.

**Comment by smowton** [comment] 2021-06-18 11:30
Duplicate of #6104

**Closed by smowton** 2021-06-18 11:30 UTC
Labels: question

**Comment by vedantmgoyal2009** [comment] 2021-06-18 11:32
Why you close my issue, please add me please... 🙏🏻
