### ISSUE TITLE
False positive: About Javascript TaintBarriers

### ISSUE THREAD

**Issue by retanoj** [github/codeql#11667] opened 2022-12-13 02:55 UTC
I give some tests about Javascript TaintBarriers library. These show when SanitizerGuardNode compares with true/false or inverts will make things wrong.  Details show as below.

I custom a Sanitizer called `CustomAdHocWhitelistCheckSanitizer` in `javascript/ql/test/library-tests/TaintBarriers/ExampleConfiguration.qll`, and make `outcome` includes  `[true,false]` in order to observe SINK points in true/false branch.

```java
class CustomAdHocWhitelistCheckSanitizer extends TaintTracking::AdHocWhitelistCheckSanitizer {
  override predicate sanitizes(boolean outcome, Expr e) {
    outcome = [true, false] and
    e = this.getArgument(0).asExpr()
  }
}
```

### First case

```javascript
1  function conditionSanitization() {
2     var v = SOURCE();
3
4     if (isWhitelisted(v)) {
5        SINK(v);
6     } else {
7        SINK(v);
8     }
9  }
```

Result as expected.

```log
+isBarrier
+isLabeledBarrier
+| ExampleConfiguration | tst.js:5:14:5:14 | v | taint |
+| ExampleConfiguration | tst.js:7:14:7:14 | v | taint |
+isSanitizer
+sanitizingGuard
+| tst.js:4:9:4:24 | isWhitelisted(v) | tst.js:4:23:4:23 | v | false |
+| tst.js:4:9:4:24 | isWhitelisted(v) | tst.js:4:23:4:23 | v | true |
+taintedSink
```

### Second case

```javascript
1  function conditionSanitization() {
2     var v = SOURCE();
3
4     if (isWhitelisted(v) === true) {
5        SINK(v);
6     } else {
7        SINK(v);
8     }
9  }
```

something wrong. SINK in line 5 and 7 are all labeled as `taintedSink`.

```log
+isBarrier
+isLabeledBarrier
+isSanitizer
+sanitizingGuard
+| tst.js:4:9:4:24 | isWhitelisted(v) | tst.js:4:23:4:23 | v | false |
+| tst.js:4:9:4:24 | isWhitelisted(v) | tst.js:4:23:4:23 | v | true |
+| tst.js:4:9:4:33 | isWhite ... == true | tst.js:4:9:4:24 | isWhitelisted(v) | true |
+| tst.js:4:9:4:33 | isWhite ... == true | tst.js:4:30:4:33 | true | true |
+taintedSink
+| tst.js:2:13:2:20 | SOURCE() | tst.js:5:14:5:14 | v |
+| tst.js:2:13:2:20 | SOURCE() | tst.js:7:14:7:14 | v |
```

### Third case

```javascript
1  function conditionSanitization() {
2     var v = SOURCE();
3
4     if (~isWhitelisted(v)) {
5        SINK(v);
6     } else {
7        SINK(v);
8     }
9  }
```

wrong. SINK in line 5 and 7 are all labeled as `taintedSink`.

```log
+isBarrier
+isLabeledBarrier
+isSanitizer
+sanitizingGuard
+| tst.js:4:10:4:25 | isWhitelisted(v) | tst.js:4:24:4:24 | v | false |
+| tst.js:4:10:4:25 | isWhitelisted(v) | tst.js:4:24:4:24 | v | true |
+taintedSink
+| tst.js:2:13:2:20 | SOURCE() | tst.js:5:14:5:14 | v |
+| tst.js:2:13:2:20 | SOURCE() | tst.js:7:14:7:14 | v |
```

**Comment by asgerf** [comment] 2022-12-13 10:45
Hi @retanoj,

Thanks for the report, again. Have you observed any FPs in real code bases arising from this issue?

**Comment by retanoj** [comment] 2022-12-14 01:33
> Hi @retanoj,
> 
> Thanks for the report, again. Have you observed any FPs in real code bases arising from this issue?

Yes. I observed this issue from working. The code remove sensetive info show as below.

```javascript
const Router = require('koa-router')
const {Sequelize} = require("sequelize");

new Router().get("/hello", (ctx) => {
    const { version } = ctx.query;

    if (version && validVersion(version) === false) {
        throw new Error(`invalid version ${version}`);
    }

    const conditions = ['1'];

    if (version) {
        conditions.push(`version = ${version}`)
    }

    new Sequelize().query(`SELECT * FROM t WHERE ${conditions.join(' and ')}`, null);
});

function validVersion(version) {
    const pattern = /^[a-zA-Z0-9]+$/;
    return pattern.test(version);
}
```

**Comment by retanoj** [comment] 2022-12-19 01:37
hi @asgerf 

May I ask this issue is blocked?
Or is there any non-technical problem？

**Comment by erik-krogh** [comment] 2022-12-19 07:43
> May I ask this issue is blocked?

Hello @retanoj 
I'm taking over, and I'll have a look at it this week.

**Comment by erik-krogh** [comment] 2022-12-20 18:53
Thanks for the example, I was able to reproduce, and make a sanitizer-guard such that no alerts are produced on your example:  

```CodeQL
class MyExtraSanitizer extends TaintTracking::SanitizerGuardNode {
  TaintTracking::SanitizerGuardNode prev;
  EqualityTest test;
  BooleanLiteral bool;
  boolean polarity;

  MyExtraSanitizer() {
    this.asExpr() = test and
    test.hasOperands(prev.asExpr(), bool) and
    polarity = test.getPolarity()
  }

  override predicate sanitizes(boolean outcome, Expr e) {
    exists(boolean prevOutcome |
      prev.sanitizes(prevOutcome, e) and
      if bool.getValue() = "true"
      then outcome = prevOutcome.booleanXor(polarity).booleanNot()
      else outcome = prevOutcome.booleanXor(polarity)
    )
  }
}
```

This sanitizer should expand all `SanitizerGuardNode`s to support such equality tests.  
(Using true/false and `==`/`!==` etc).  

I would prefer it to be a `BarrierGuardNode` instead of a `SanitizerGuardNode` to generalize further.   
But that introduces some negative recursion that will take some more effort to fix.  

I'm looking into a generalization right now, but I don't expect that to be merged this year.   
So in the meantime you can use the above.

**Comment by retanoj** [comment] 2022-12-21 04:38
> Thanks for the example, I was able to reproduce, and make a sanitizer-guard such that no alerts are produced on your example:
> 
> ```ql
> class MyExtraSanitizer extends TaintTracking::SanitizerGuardNode {
>   TaintTracking::SanitizerGuardNode prev;
>   EqualityTest test;
>   BooleanLiteral bool;
>   boolean polarity;
> 
>   MyExtraSanitizer() {
>     this.asExpr() = test and
>     test.hasOperands(prev.asExpr(), bool) and
>     polarity = test.getPolarity()
>   }
> 
>   override predicate sanitizes(boolean outcome, Expr e) {
>     exists(boolean prevOutcome |
>       prev.sanitizes(prevOutcome, e) and
>       if bool.getValue() = "true"
>       then outcome = prevOutcome.booleanXor(polarity).booleanNot()
>       else outcome = prevOutcome.booleanXor(polarity)
>     )
>   }
> }
> ```
> 
> This sanitizer should expand all `SanitizerGuardNode`s to support such equality tests. (Using true/false and `==`/`!==` etc).
> 
> I would prefer it to be a `BarrierGuardNode` instead of a `SanitizerGuardNode` to generalize further. But that introduces some negative recursion that will take some more effort to fix.
> 
> I'm looking into a generalization right now, but I don't expect that to be merged this year. So in the meantime you can use the above.

em.. thx @erik-krogh , I need to go into `MyExtraSanitizer`

**Comment by retanoj** [comment] 2022-12-21 11:03
Hi @erik-krogh ,
I've figured it out. And in view of Third case, I write a `BitNotExprSanitizer`.

```java
class BitNotExprSanitizer extends TaintTracking::SanitizerGuardNode {
  TaintTracking::SanitizerGuardNode prev;
  BitNotExpr test;

  BitNotExprSanitizer() {
    this.asExpr() = test and
    prev.asExpr() = test.getOperand()
  }

  override predicate sanitizes(boolean outcome, Expr e) {
    exists(boolean prevOutcome |
      prev.sanitizes(prevOutcome, e) and
      outcome = prevOutcome.booleanNot()
    ) 
  }
}
```

**Comment by erik-krogh** [comment] 2022-12-21 15:39
> I've figured it out. And in view of Third case, I write a `BitNotExprSanitizer`.

I'm not going to support the `~` operator like that in our standard libraries, because `~` is not a "not operator" on booleans.  

E.g. `~true  === -2` and `~false === -1`.   
`-1` and `-2` are truthy, so it just doesn't work as a not operator.   

`!` is the operator that should be used for booleans.  
We could have a query flag flags uses of `~` in conditionals, because that seems like a mistake on it's own.

**Closed** 2023-02-27 14:48 UTC
Labels: false-positive

**Comment by erik-krogh** [comment] 2023-02-27 14:50
The issue was fixed with https://github.com/github/codeql/pull/11769. 

It will still take a few weeks for the fix to be deployed to code-scanning, but it should work now if you use the latest code from `github/codeql` yourself.
