### ISSUE TITLE
LGTM.com - false positive "self comparison" on template parameters

### ISSUE THREAD

**Issue by tido64** [github/codeql#2950] opened 2020-02-29 16:20 UTC
**Description of the false positive**

LGTM warns about self comparison in `std::is_signed_v<T> != std::is_signed_v<U>` but doesn't consider the previous assertion `!std::is_same_v<T, U>`.

**URL to the alert on the project page on LGTM.com**

Alert: https://lgtm.com/projects/g/tido64/rainbow/snapshot/52ab63317fcb26cef39c0914184c13dacfba6341/files/src/Common/TypeCast.h?sort=name&dir=ASC&mode=heatmap#x98a66abd4a553a6:1

Attempt to "fix" it: https://lgtm.com/projects/g/tido64/rainbow/rev/pr-2419da0e4016f1fced85f2ad2e85f2f302877a2d

**Comment by jimis** [comment] 2020-07-06 15:01
We also got this false positive, see:
https://lgtm.com/projects/g/qt/qtbase/snapshot/379a5619f8a39dc5a7a111acbbf90a5e899d53c1/files/src/corelib/global/qglobal.h?sort=name&dir=ASC&mode=heatmap#xc052b7cbd78a48bc:1

**Comment by jbj** [comment] 2020-07-07 16:17
Thanks for bumping this issue. It had fallen between the cracks.

The alert goes away if I add `not cmp.getLeftOperand().(VariableAccess).getTarget().isFromTemplateInstantiation(_)` to the `where` clause of the query, but that would be a very specific workaround.

The query is supposed to filter out template results via https://github.com/github/codeql/blob/22666dd46e0262f761d98d904f93f875680c09a8/cpp/ql/src/Likely%20Bugs/Arithmetic/PointlessSelfComparison.ql#L23, but I'm guessing that this doesn't work because the concept of being inside a template is linked to the concept of an enclosing element, and our modelling of enclosing elements goes through statements and expressions. A `static_assert` is modelled as https://github.com/github/codeql/blob/22666dd46e0262f761d98d904f93f875680c09a8/cpp/ql/src/semmle/code/cpp/Element.qll#L275 which is not a type of element that can have a parent even though [the language reference says `static_assert` is a _declaration_](https://en.cppreference.com/w/cpp/language/static_assert) and so should fit in a _declaration statement_.

@igfoo, is there a way the extractor can tell us that these expressions like `std::is_signed_v<T>` are from instantiated templates? With or without telling us what the template is.

**Comment by jbj** [comment] 2020-07-09 07:36
The first half of the fix is in progress: https://github.com/github/codeql/pull/3929.

**Comment by igfoo** [comment] 2020-07-21 14:05
It looks like the remainder of the fix is going to require a bit more work under the hood, so I'm afraid it'll probably be a few months before we're able to complete this.

**Comment by jbj** [comment] 2020-11-12 13:19
I can no longer reproduce these false positives, and they don't show up in https://lgtm.com/projects/g/qt/qtbase/alerts/?mode=tree. Please reopen this issue if they still apply.

**Closed by jbj** 2020-11-12 13:19 UTC
Labels: C++, false-positive

**Comment by tido64** [comment] 2020-11-13 09:30
@jbj: Thanks for fixing this. It's working on our end ❤️
