### ISSUE TITLE
CodeQL runs failing with link to experimental-atm-queries that are not configured

### ISSUE THREAD

**Issue by rajbos** [github/codeql#11305] opened 2022-11-16 14:18 UTC
**Description of the issue**
My CodeQL run is failing all of a sudden (I don't see any changes of the workflow) with a link to an experimental query. I do have a config file that specifies the run of extra queries:
``` yaml
paths:
  - src
  - packages.json
  - package-lock.json
queries:
  - uses: security-and-quality
  - uses: security-extended
```

For the workflow logs, you can check here: [link](https://github.com/devops-actions/load-available-actions/actions/runs/3479820803/jobs/5818834280).

Interesting part in the logs:
```
  [202/202 eval 1s] Evaluation done; writing results to codeql/javascript-queries/Summary/LinesOfUserCode.bqrs.
  Shutting down query evaluator.
  /opt/hostedtoolcache/CodeQL/0.0.0-20221024/x64/codeql/codeql database run-queries --ram=5920 --threads=2 /home/runner/work/_temp/codeql_databases/javascript --min-disk-free=1024 -v /home/runner/work/_temp/codeql_databases/javascript-queries-packs.qls
  Writing logs to /home/runner/work/_temp/codeql_databases/javascript/log/database-run-queries-20221116.133817.339.log.
  Writing logs to /home/runner/work/_temp/codeql_databases/javascript/log/execute-queries-20221116.133817.886.log.
  A fatal error occurred: The QL pack 'codeql/javascript-experimental-atm-queries@~0.3.0' which is referenced from /home/runner/work/_temp/codeql_databases/javascript-queries-packs.qls cannot be found.
  Error: Failure invoking /opt/hostedtoolcache/CodeQL/0.0.0-20221024/x64/codeql/codeql with arguments database,run-queries,--ram=5920,--threads=2,/home/runner/work/_temp/codeql_databases/javascript,--min-disk-free=1024,-v,/home/runner/work/_temp/codeql_databases/javascript-queries-packs.qls.
```

Anything that I should do to fix this?

**Comment by edoardopirovano** [comment] 2022-11-16 15:45
Greetings! Our apologies that you encountered this issue, this was caused by some internal changes to our code that contained a bug. We've now rolled back the problematic change, so everything should be working for you again. I'm going to go ahead and close this issue as we're fairly confident this shouldn't occur again, but please do open it again if the problem resurfaces.

**Closed by edoardopirovano** 2022-11-16 15:45 UTC
Labels: question

**Comment by rajbos** [comment] 2022-11-16 20:54
Thanks!
