### ISSUE TITLE
Error running query SignedOverflowCheck.ql: ExecutionFailed

### ISSUE THREAD

**Issue by gbedoya** [github/codeql#3549] opened 2020-05-22 21:24 UTC
The following C/C++ build analysis on the open-source osquery project fails.

Details
```
[2020-05-22 20:51:50] [analysis] [EVALUATION 47/150] [FAIL] Error running query semmlecode-cpp-queries/Likely Bugs/Arithmetic/SignedOverflowCheck.ql: ExecutionFailed
                                 com.semmle.util.concurrent.UnhandledAsyncException: 3 asynchronous exceptions caught
                                 com.semmle.util.concurrent.CancellationToken.checkCancelled(CancellationToken.java:160)
                                 com.semmle.inmemory.relations.ProgramEvaluator.evaluatePredicate(ProgramEvaluator.java:567)
                                 com.semmle.inmemory.relations.ProgramEvaluator.lambda$null$20(ProgramEvaluator.java:718)
                                 java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
                                 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
                                 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                                 java.lang.Thread.run(Thread.java:748)
```

Analysis URL ...
https://lgtm.com/projects/g/osquery/osquery/logs/rev/pr-37d866e7ecf817a357cf2bf4bca184b7e657dcd8/lang:cpp/stage:Build%20merge_ff4f037a9183c9779f26c8baa46bce156e9723fe

**Comment by jbj** [comment] 2020-05-28 08:00
Thank you for the report. We're investigating.

**Comment by geoffw0** [comment] 2020-06-09 12:56
Unfortunately this issue is proving a little difficult to track down, please continue to be patient with us!

**Comment by gbedoya** [comment] 2020-06-09 22:45
@geoffw0 should I see the error again in new build I can open a new ticket. Are you good with closing as unreproducible?

**Comment by geoffw0** [comment] 2020-06-11 18:18
Yes that's fine.  The problem is being investigated internally by the appropriate team, but if it isn't affecting you at this time, by all means close the issue.  If you do open a new ticket, it would be helpful to provide a link back to this one for context - thanks!

**Closed** 2020-06-11 19:21 UTC
Labels: C++, question
