### ISSUE TITLE
go 1.21 support

### ISSUE THREAD

**Issue by vadimi-ep** [github/codeql#13992] opened 2023-08-17 15:44 UTC
Hello, we are trying to scan a repo that uses go 1.21, but getting the following error from the codeql autobuild step:

```
Error: 2023/08/17 15:21:38   /opt/hostedtoolcache/go/1.21.0/x64/src/slices/sort.go:67:7: undefined: min
  Error: 2023/08/17 15:21:38   /opt/hostedtoolcache/go/1.21.0/x64/src/slices/sort.go:97:7: undefined: max
  2023/08/17 15:21:38   -: This application uses version go1.20 of the source-processing packages but runs version go1.21 of 'go list'. It may fail to process source files that rely on newer language features. If so, rebuild the application using a newer version of Go.
```

**Comment by aibaars** [comment] 2023-08-17 16:12
Thanks for reporting. Are you using Go 1.21 in your workflow? You can use https://github.com/actions/setup-go to select the right go version.

**Comment by mbg** [comment] 2023-08-17 16:48
Hi @vadimi-ep! Those errors are expected with the current CodeQL release and shouldn't get in the way of your analysis. They will go away in the next CodeQL release.

See https://github.com/github/codeql/pull/13867#issuecomment-1679033611 for my answer to an earlier question about this.

**Comment by vadimi-ep** [comment] 2023-08-17 17:50
yes, go 1.21 is used through setup-go action.

@mbg thanks for this

**Comment by AlekSi** [comment] 2023-09-07 18:34
go-extractor fails with:
> invalid go version '1.21.1': must match format 1.23

But Go 1.21 allows directives like `go 1.21.1` in go.mod files. From https://go.dev/blog/toolchain

> Starting in Go 1.21, Go toolchains will treat the go line in go.mod not as a guideline but as a rule, and the line can list specific point releases or release candidates. That is, Go 1.21.0 understands that it cannot even build code that says go 1.21.1 in its go.mod file, not to mention code that says much later versions like go 1.22.0.

**Comment by mbg** [comment] 2023-09-08 13:38
@AlekSi that should not be happening with the latest releases of CodeQL. Can you confirm which version of the CodeQL CLI you are using and that you have Go 1.21 installed on the machine that you are running this on? See e.g. https://github.com/github/codeql-action/issues/1842

**Comment by AlekSi** [comment] 2023-09-08 13:40
I don't have any configuration for CodeQL other than a settings toggle. The output is here: https://github.com/FerretDB/FerretDB/actions/runs/6120237173/job/16611693348

**Comment by jon-whit** [comment] 2023-09-12 21:40
I'm still seeing this issue even despite the recent release 7 hours ago. What's the ETA? It's blocking some builds.
<img width="756" alt="Screenshot 2023-09-12 at 3 37 51 PM" src="https://github.com/github/codeql/assets/2899204/f5466336-7ab2-414a-82d1-c1c561124fe3">

**Comment by mbg** [comment] 2023-09-12 23:38
@jon-whit New CLI releases aren't immediately used by the CodeQL Action. There's always a short delay between the CLI release and it becoming the default used by the Action. Assuming that your question relates to the `openfga/openfga` repository, I can see that your most recent CodeQL run still used version 2.14.3 of the CLI. Once the Action uses the new CLI release, you should see the error disappear.

**Comment by sidshank** [comment] 2023-09-13 00:07
@jon-whit CodeQL Action workflows across GitHub should start using the new CodeQL CLI over the next 24-48 hours.

**Comment by jon-whit** [comment] 2023-09-13 15:40
@mbg @sidshank thanks

**Comment by taigrr** [comment] 2023-09-26 01:42
the /x/tools package is still out of date, preventing the go analysis tools from loading correctly for me. 

I think this might help:
https://github.com/github/codeql/pull/14314

**Comment by mbg** [comment] 2023-09-26 14:25
@taigrr thanks for opening that PR, I will have a look at it. However, I don't think your problem is caused by an out-of-date version of `/x/tools`. Looking at your CodeQL workflow runs, it looks like they all [ran with Go 1.20](https://github.com/gogrlx/grlx/actions/runs/6302926499/job/17111098056#step:4:46). Can you look at my instructions in https://github.com/github/codeql-action/issues/1842#issuecomment-1704398087 to install Go 1.21 for your CodeQL workflow?

**Comment by taigrr** [comment] 2023-09-26 15:39
That fix [definitely helped](https://github.com/gogrlx/grlx/actions/runs/6314986929/job/17146497876), as I would expect. I was under the impression the `/x/tools` update would help the automatic version detection work correctly with the x.y.z version format, but maybe I'm wrong. I know I saw an update to `x/tools` recently helped my LSP figure out the new version format, and I saw the same error message issue here.

**Comment by mbg** [comment] 2023-09-26 16:27
@taigrr No problem, it makes sense that you would have jumped to that conclusion based on your experience with the LSP! We had [already upgraded `/x/tools` to a version that supports the new version format around the time that Go 1.21 was released](https://github.com/github/codeql/pull/13923), so there shouldn't have been any issues with that. 

I am aware of one issue we had with the new version format recently, but that [got patched](https://github.com/github/codeql/pull/14234) as well, and would have manifested differently.

**Comment by mbg** [comment] 2024-03-18 12:25
I forgot to close this, but Go 1.21 support shipped back in October.

**Closed by mbg** 2024-03-18 12:25 UTC
Labels: question, acknowledged
