### ISSUE TITLE
StackOverflow error on index files

### ISSUE THREAD

**Issue by theveriton** [github/codeql#15661] opened 2024-02-20 11:08 UTC
Suddenly, Perform CodeQL Analysis step has started failing on index files step.

github/codeql-action/analyze@v2

I've tried using v3 too with no luck

Also, I've tried increasing thread heap size from 2M all the way to 512M with no luck

```
E:\actions-runner-ghec\_work\_tool\CodeQL\2.16.2\x64\codeql\codeql.exe database finalize --finalize-dataset --threads=12 --ram=30002 E:\actions-runner-ghec\_work\_temp\codeql_databases\java
  Picked up JAVA_TOOL_OPTIONS: -Xss512m
  Running pre-finalize script E:\actions-runner-ghec\_work\_tool\CodeQL\2.16.2\x64\codeql\java\tools\pre-finalize.cmd in E:\actions-runner-ghec\_work\test-test-appserver\test-test-appserver.
  [2024-02-20 03:25:52] [build-stderr] Picked up JAVA_TOOL_OPTIONS: -Xss512m
  [2024-02-20 03:25:52] [build-stderr] Scanning for files in E:\actions-runner-ghec\_work\test-test-appserver\test-test-appserver...
  [2024-02-20 03:25:52] [build-stderr] E:\actions-runner-ghec\_work\_temp\codeql_databases\java: Indexing files in in E:\actions-runner-ghec\_work\test-test-appserver\test-test-appserver...
  [2024-02-20 03:25:53] [build-stderr] Running command in E:\actions-runner-ghec\_work\test-test-appserver\test-test-appserver: [E:\actions-runner-ghec\_work\_tool\CodeQL\2.16.2\x64\codeql\xml\tools\index-files.cmd, E:\actions-runner-ghec\_work\_temp\codeql_databases\java\working\files-to-index18386133814325443289.list]
  [2024-02-20 03:25:53] [build-stdout] [2024-02-20 03:25:53] [build-stderr] Picked up JAVA_TOOL_OPTIONS: -Xss512m
  [2024-02-20 03:25:55] [build-stderr] Picked up JAVA_TOOL_OPTIONS: -Xss512m
  [2024-02-20 03:25:55] [build-stderr] Scanning for files in E:\actions-runner-ghec\_work\test-test-appserver\test-test-appserver...
  [2024-02-20 03:25:56] [build-stderr] E:\actions-runner-ghec\_work\_temp\codeql_databases\java: Indexing files in in E:\actions-runner-ghec\_work\test-test-appserver\test-test-appserver...
  [2024-02-20 03:25:56] [build-stderr] Running command in E:\actions-runner-ghec\_work\test-test-appserver\test-test-appserver: [E:\actions-runner-ghec\_work\_tool\CodeQL\2.16.2\x64\codeql\properties\tools\index-files.cmd, E:\actions-runner-ghec\_work\_temp\codeql_databases\java\working\files-to-index182820796413[80](https://github.com/testsomeorg/test-test-appserver/actions/runs/7971172665/job/21760290942#step:6:81)0805[88](https://github.com/testsomeorg/test-test-appserver/actions/runs/7971172665/job/21760290942#step:6:89).list]
  [2024-02-20 03:25:56] [build-stdout] [2024-02-20 03:25:56] [build-stderr] Picked up JAVA_TOOL_OPTIONS: -Xss512m
  [2024-02-20 03:25:56] [build-stdout] [2024-02-20 03:25:56] [build-stderr] Exception in thread "main" java.lang.StackOverflowError
  [2024-02-20 03:25:56] [build-stdout] [2024-02-20 03:25:56] [build-stderr] 	at java.base/java.util.regex.Pattern$GroupHead.match(Unknown Source)
  [2024-02-20 03:25:56] [build-stdout] [2024-02-20 03:25:56] [build-stderr] 	at java.base/java.util.regex.Pattern$Loop.match(Unknown Source)
  [2024-02-20 03:25:56] [build-stdout] [2024-02-20 03:25:56] [build-stderr] 	at java.base/java.util.regex.Pattern$GroupTail.match(Unknown Source)
  [2024-02-20 03:25:56] [build-stdout] [2024-02-20 03:25:56] [build-stderr] 	at java.base/java.util.regex.Pattern$BranchConn.match(Unknown Source)
  [2024-02-20 03:25:56] [build-stdout] [2024-02-20 03:25:56] [build-stderr] 	at java.base/java.util.regex.Pattern$CharProperty.match(Unknown Source)
  [2024-02-20 03:25:56] [build-stdout] [2024-02-20 03:25:56] [build-stderr] 	at java.base/java.util.regex.Pattern$Branch.match(Unknown Source)
  [2024-02-20 03:25:56] [build-stdout] [2024-02-20 03:25:56] [build-stderr] 	at java.base/java.util.regex.Pattern$GroupHead.match(Unknown Source)
  [2024-02-20 03:25:56] [build-stdout] [2024-02-20 03:25:56] [build-stderr] 	at java.base/java.util.regex.Pattern$Loop.match(Unknown Source)
  [2024-02-20 03:25:56] [build-stdout] [2024-02-20 03:25:56] [build-stderr] 	at java.base/java.util.regex.Pattern$GroupTail.match(Unknown Source)
  [2024-02-20 03:25:56] [build-stdout] [2024-02-20 03:25:56] [build-stderr] 	at java.base/java.util.regex.Pattern$BranchConn.match(Unknown Source)
  [2024-02-20 03:25:56] [build-stdout] [2024-02-20 03:25:56] [build-stderr] 	at java.base/java.util.regex.Pattern$CharProperty.match(Unknown Source)
```

**Comment by aibaars** [comment] 2024-02-20 12:18
Duplicate https://github.com/github/codeql-action/issues/2155

**Comment by sidshank** [comment] 2024-02-26 01:18
Closing this issue since it is a duplicate of https://github.com/github/codeql-action/issues/2155

**Closed by sidshank** 2024-02-26 01:18 UTC
Labels: duplicate, question
