### ISSUE TITLE
xnu-6153.141.1 codeql database creation fails after building the kernel

### ISSUE THREAD

**Issue by cutecodee** [github/codeql#4901] opened 2021-01-03 15:13 UTC
i tried to create a codeql database for xnu-6153.141.1, the kernel compiles just fine, but after the compilation is done, codeql gives me some errors (if i try to compile xnu without codelq, it doesn't give me any error, so i think it's codeql related)
here is the complete log: https://pastebin.com/AvY1Mx33

**Comment by criemen** [comment] 2021-01-04 11:12
Hi,
I've spent now some time but I am still unable to build the kernel clean (without codeql).
Can you provide me with some more information:
- What OS version are you using?
- What XCode version are you using for building XNU?
- Are you using any of the build scripts that are floating aroung on gist, if yes, which one?

**Comment by criemen** [comment] 2021-01-04 12:08
Can you also please zip up the folder `xnu-6153.141.1/log` and attach it to the issue?

I managed to reduce the makefiles on my system to only execute the INSTALLPY steps and I am unfortunately unable to reproduce the issue without further information.

**Comment by cutecodee** [comment] 2021-01-04 13:24
> Hi,
> I've spent now some time but I am still unable to build the kernel clean (without codeql).
> Can you provide me with some more information:
> 
>     * What OS version are you using?
> 
>     * What XCode version are you using for building XNU?
> 
>     * Are you using any of the build scripts that are floating aroung on gist, if yes, which one?

Hi, I'm using macOS Mojave 10.14.6, with Xcode 11.3.1 (11C505), I've patched the xnu files to make it compile, you can find all the steps [here](https://kernelshaman.blogspot.com/2020/09/building-xnu-for-macos-catalina-1015x.html).
here is [log.zip](https://github.com/github/codeql/files/5764853/log.zip)
thanks in advance

**Comment by criemen** [comment] 2021-01-04 16:50
I'm still working on reproducing the issue, but can you post the output of `codeql --version` in the meantime?

**Comment by cutecodee** [comment] 2021-01-05 08:31
> I'm still working on reproducing the issue, but can you post the output of `codeql --version` in the meantime?

That's the output:

MBP-di-Tommaso:xnu-codeql cutesmilee$ codeql/codeql --version
CodeQL command-line toolchain release 2.4.1.
Copyright (C) 2019-2020 GitHub, Inc.
Unpacked in: /Users/cutesmilee/Desktop/xnu-codeql/codeql
   Analysis results depend critically on separately distributed query and
   extractor modules. To list modules that are visible to the toolchain,
   use 'codeql resolve qlpacks' and 'codeql resolve languages'.

**Comment by criemen** [comment] 2021-01-06 09:05
I investigated this issue further yesterday, and can reproduce it locally.
I don't have an ETA on a fix, but I can offer you two workarounds so you can get started with building the database:
* Upgrade your OS to Catalina - on 10.15.7 I cannot reproduce the error
* OR: in the kernel sources in `makedefs/MakeInc.rule`, delete the two lines
```cpp
	$$(PYTHON) $$(LLDBMACROS_SOURCE)/core/syntax_checker.py \
		./$(3)/$$*.unifdef.$$$$$$$$$$(suffix $$*) $$(_vstdout) || exit 1; \
```

**Comment by cutecodee** [comment] 2021-01-06 16:02
> I investigated this issue further yesterday, and can reproduce it locally.
> I don't have an ETA on a fix, but I can offer you two workarounds so you can get started with building the database:
> 
>     * Upgrade your OS to Catalina - on 10.15.7 I cannot reproduce the error
> 
>     * OR: in the kernel sources in `makedefs/MakeInc.rule`, delete the two lines
> 
> 
> ```c++
> 	$$(PYTHON) $$(LLDBMACROS_SOURCE)/core/syntax_checker.py \
> 		./$(3)/$$*.unifdef.$$$$$$$$$$(suffix $$*) $$(_vstdout) || exit 1; \
> ```

It worked! Thanks a lot!

**Comment by criemen** [comment] 2021-01-08 12:15
Closing this, as we will ship a proper fix for this issue in the next release of the CodeQL CLI.

**Closed by criemen** 2021-01-08 12:15 UTC
Labels: C++, bug, question
